### ISSUE TITLE
project doesnt compile with jdk 1.7.0_55 and Maven 3.2.1

### ISSUE THREAD

**Issue by javabeanz** [jmanico/owasp-java-encoder#1]
I am missing some files like :
org.owasp.esapi.codecs.Codec;
org.owasp.esapi.errors.EncodingException;
org.owasp.esapi.reference.DefaultEncoder;
....

When I do a mvn install, I get : 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
2:compile (default-compile) on project encoder-esapi: Compilation failure: Compi
lation failure:
[ERROR] /D:/projects/owasp-java-encoder/esapi/src/main/java/org/owasp/encoder/es
api/ESAPIEncoder.java:[39,23] package org.owasp.esapi does not exist
[ERROR] /D:/projects/owasp-java-encoder/esapi/src/main/java/org/owasp/encoder/es
api/ESAPIEncoder.java:[40,30] package org.owasp.esapi.codecs does not exist
[ERROR] /D:/projects/owasp-java-encoder/esapi/src/main/java/org/owasp/encoder/es
api/ESAPIEncoder.java:[41,30] package org.owasp.esapi.errors does not exist
[ERROR] /D:/projects/owasp-java-encoder/esapi/src/main/java/org/owasp/encoder/es
api/ESAPIEncoder.java:[42,33] package org.owasp.esapi.reference does not exist
[ERROR] /D:/projects/owasp-java-encoder/esapi/src/main/java/org/owasp/encoder/es
api/ESAPIEncoder.java:[114,19] cannot find symbol
[ERROR] symbol:   class Encoder
[ERROR] location: class org.owasp.encoder.esapi.ESAPIEncoder
[ERROR] /D:/projects/owasp-java-encoder/esapi/src/main/java/org/owasp/encoder/es
api/ESAPIEncoder.java:[128,34] cannot find symbol
[ERROR] symbol:   class Encoder

**Comment by xeno6696** [comment]
Interesting.  When I was at work I had an identical problem, but now on my laptop it's fine:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] OWASP Encoders Parent ............................. SUCCESS [21.696s]
[INFO] OWASP Encoders .................................... SUCCESS [52.657s]
[INFO] OWASP Encoders JSP tags and EL functions .......... SUCCESS [3.457s]
[INFO] OWASP Encoders ESAPI Thunk ........................ SUCCESS [4.536s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:24.020s
[INFO] Finished at: Mon Apr 13 14:49:09 CDT 2015
[INFO] Final Memory: 24M/107M
[INFO] ------------------------------------------------------------------------
[user@personal owasp-java-encoder]$ java --version
Unrecognized option: --version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
[user@personal owasp-java-encoder]$ java -version
java version "1.7.0_75"
OpenJDK Runtime Environment (fedora-2.5.4.2.fc20-x86_64 u75-b13)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
[user@personal owasp-java-encoder]$ 

Important to note, at work I think I was running Oracle JDK 1.7_60.  I'll retest tommorrow. 

Maven version:

[user@personal owasp-java-encoder]$ mvn --version
Apache Maven 3.1.1 (NON-CANONICAL_2015-03-16_14-07_mockbuild; 2015-03-16 09:07:43-0500)
Maven home: /usr/share/maven
Java version: 1.7.0_75, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.75-2.5.4.2.fc20.x86_64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.12.23-1.pvops.qubes.x86_64", arch: "amd64", family: "unix"

**Comment by jmanico** [comment]
I'm sorry I missed this issue. Noted, now. Do you have any more information to share? Are we ok to close this issue or is it still a problem?

Aloha,
Jim
Jim@owasp.org

**Comment by javabeanz** [comment]
Works OK now. Maybe my maven repo was corrupted with a local build of the esapi library.
