### ISSUE TITLE
Modernize and validate the Maven Central signing and release workflow

### ISSUE THREAD

**Issue by jmanico** [jmanico/owasp-java-encoder#95]
Follow-up to #90 (reviewed at `31588e1`). This tracks work intentionally kept separate from the modernization PR.

## Current state

The root POM still uses `org.sonatype.oss:oss-parent:9`, Maven GPG Plugin `1.6`, and Central Publishing Plugin `0.9.0`. Ordinary `clean verify` and CI success do not validate the signing/publishing lifecycle.

This is release-tooling maintenance, not a request to publish a release or change credentials.

## Acceptance criteria

- [ ] Audit inherited behavior from `oss-parent`; replace or remove it only after explicitly preserving required metadata and lifecycle behavior.
- [ ] Update and pin signing/publishing tooling to versions validated for the project's chosen Maven/JDK baseline.
- [ ] Document noninteractive signing, credential requirements, local validation, staging/review, and recovery from a failed release attempt.
- [ ] Validate binaries, sources, Javadocs, POMs, signatures, and checksums in an isolated local/staging workflow that cannot accidentally publish publicly.
- [ ] Verify all four artifacts preserve the consumer contract: coordinates, scopes, public APIs, Java baseline, automatic/explicit module names, OSGi metadata, and TLDs.
- [ ] Confirm the optional Jakarta test WAR is not unintentionally included in a library release.
- [ ] Keep production publication explicitly maintainer-controlled and keep credentials out of logs and PR workflows.
- [ ] Document reproducibility expectations, including generated manifest timestamps, and fix controllable nondeterminism where practical.

Reference: [Sonatype's Maven publishing documentation](https://central.sonatype.org/publish/publish-portal-maven/).

**Comment by jmanico** [comment]
A follow-up review of `main` @ `94fd425` found additional items for this issue:

The body scopes this out of "change credentials", but today only one person can publish at all, so the items below widen the acceptance criteria rather than open a separate issue.

- [ ] Register a second publisher on the `org.owasp.encoder` namespace in the Central Portal with their own user token. Evidence: `git for-each-ref refs/tags` shows tagger Jeremy Long on all seven tags (v1.2 through v1.4.0); `gh api repos/OWASP/owasp-java-encoder/releases` shows author=jeremylong on all four releases; the `owasp-java-encoder` team has two members, but the second maintainer holds no Portal token, and Sonatype's current Portal documentation authenticates only with a per-user token in `settings.xml`. If the one releaser is unavailable, no release can reach the 4,666 repositories on the dependents page. Criterion: both maintainers are publishers for the namespace and each holds a token in a local `settings.xml` that is never committed.
- [ ] Give the second maintainer a non-expired signing key published to keyserver.ubuntu.com and keys.openpgp.org. Evidence: `gpg --list-packets` on the Central `encoder-1.3.0`, `1.3.1` and `1.4.0` `.asc` files gives key `FFDE55BE73A2D1ED` every time, and the `1.4.0` jar manifest reports `Built-By: jeremy`, `Build-Jdk: 17.0.16`; the second maintainer's only local secret key expired on 2021-04-10, and the Portal requires a PGP `.asc` on every file. Criterion: the key resolves on both keyservers and a `.asc` it produces passes `gpg --verify` (listing it in a KEYS file is tracked separately).
- [ ] Rehearse the Portal publish: each maintainer runs `mvn clean deploy -DperformRelease=true` (the only release documentation today, `README.md:121-125`) from a fresh `-Dmaven.repo.local` on JDK 17 with `autoPublish=false` (`pom.xml:387`), lets the Portal validate the deployment, then drops it without publishing. This doubles as the isolated staging validation already listed above. Criterion: one validated-then-dropped deployment per maintainer, with their own token and key, before the next release day.
- [ ] Record the recovery path if both maintainers are unavailable: the namespace is verified through owasp.org, so the OWASP Foundation is the last-resort route to re-verify `org.owasp.encoder` and add a publisher. Criterion: the path is written into the release documentation.

Related: #103

**Comment by jmanico** [comment]
A follow-up review of `main` @ `94fd425` and of the repository settings, checked on 2026-09-23, found additional items for this issue:

- [ ] **Sign release tags from 1.4.1 onward.** `git tag -v v1.3.0`, `git tag -v v1.3.1` and `git tag -v v1.4.0` each print `error: no signature found`; the GitHub tags API reports `verification.reason` `unsigned` for all three, and `refs/tags/v1.4.0` is an unsigned annotated tag (`c6ec4c7`) pointing at `a4cdb46`. #48 (2021) asked for signed artifacts; two "next release" replies promised it and the issue was closed in 2022 with no change in 1.3.x or 1.4.0. Acceptance: `v1.4.1` is created with `git tag -s` using the key that signs the Central artifacts (currently `FFDE55BE73A2D1ED`), `git tag -v v1.4.1` verifies, and the tag shows Verified on GitHub; the release documentation this issue already asks for includes the signing step.

- [ ] **Add a tag ruleset for `refs/tags/v*` before the `v1.4.1` tag is pushed.** `gh api 'repos/OWASP/owasp-java-encoder/rulesets?targets=tag'` returns `[]`; the only ruleset targets branches, and `rules/branches/v1.4.0` returns `[]`, so no rule applies to release tags. All 8 push-capable accounts and the `owasp-java-encoder` team are admins, so any of them can retag or delete `v1.4.0` silently. The ruleset must have `bypass_actors: []`: an admin-role bypass would exempt every account that can push and make the ruleset a no-op. Tag creation stays allowed so the manual tag push keeps working.

  ```
  gh api -X POST repos/OWASP/owasp-java-encoder/rulesets --input - <<'EOF'
  {"name":"release-tags","target":"tag","enforcement":"active",
   "conditions":{"ref_name":{"include":["refs/tags/v*"],"exclude":[]}},
   "bypass_actors":[],
   "rules":[{"type":"update"},{"type":"deletion"},{"type":"non_fast_forward"}]}
  EOF
  ```

  Acceptance: `gh api 'repos/OWASP/owasp-java-encoder/rulesets?targets=tag' --jq '.[].name'` prints `release-tags`. With no bypass actor, a mistaken `v*` tag can only be corrected by an admin temporarily editing the ruleset; the release documentation states this.

- [ ] **Defer `required_signatures` on the tag ruleset.** `v1.4.0` is unsigned, so that rule would block the current release process today. Acceptance: it is added only after at least one signed release tag exists.

- [ ] **Record the tag in the published POM.** The 1.4.0 POM on Central has no `<scm><tag>`, so the git tag is the only link between the Central artifacts and the source. Acceptance: the release commit sets `<scm><tag>v1.4.1</tag>` and the 1.4.1 POM on Central carries it.

Related: #103

**Comment by jmanico** [comment]
A follow-up review of `main` @ `94fd425` found additional items for this issue:

- [ ] **Drop the `org.sonatype.oss:oss-parent:9` parent (`pom.xml:77-81`).** `mvn help:effective-pom` shows every module inherits a `sonatype-nexus-snapshots` repository (`https://oss.sonatype.org/content/repositories/snapshots`, snapshots enabled) and a `<distributionManagement>` targeting `https://oss.sonatype.org/service/local/staging/deploy/maven2/`; `curl` returns `404` for the first and `402` for the second, and the published `encoder-parent-1.4.0.pom` on Central chains to the same parent. The deploy target is inert only because `central-publishing-maven-plugin` runs with `extensions=true` (`pom.xml:381-389`). Licenses, scm, developers and `project.build.sourceEncoding` are already declared locally, so removing the parent needs no replacement metadata. Acceptance: `mvn help:effective-pom | grep -c oss.sonatype.org` prints `0` and no `sonatype-oss-release` profile remains (if activated it would pin `maven-source-plugin` 2.1.2, `maven-javadoc-plugin` 2.7 and `maven-gpg-plugin` 1.1 ahead of the root `pluginManagement`).
- [ ] **Replace the inherited `maven-enforcer-plugin` 1.2 execution.** oss-parent's `enforce-maven` execution (rule `requireMavenVersion (,2.1.0),(2.1.0,2.2.0),(2.2.0,)`, which cannot fail) runs on `encoder-parent`, `encoder`, `encoder-jsp` and `encoder-jakarta-jsp` (`--- enforcer:1.2:enforce (enforce-maven) @ encoder`); only `encoder-esapi` runs it under 3.6.3 because `esapi/pom.xml:81` overrides the version. Its resolved closure is maven-core 2.0.9, plexus-utils 1.5.8, plexus-archiver 1.0-alpha-7, jsch 0.1.27 and commons-lang 2.3. `mvn -Dmaven.plugin.validation=VERBOSE validate` reports `Plugin is a Maven 2.x plugin, which will be not supported in Maven 4.x`, and on Maven 4.0.0-rc-6 it fails with `NoSuchMethodError PluginParameterExpressionEvaluator.<init>`. A `<pluginManagement>` pin does not override it (oss-parent sets the version in `<build><plugins>`); a root `<build><plugins>` declaration of 3.6.3 does, and with only that change the full reactor builds on 4.0.0-rc-6 with the core and jakarta `MANIFEST.MF` identical to the Maven 3 output apart from timestamps. Acceptance: `mvn validate | grep enforcer` shows only `enforcer:3.6.3` and the verbose validation warning is gone.
- [ ] **One root enforcer execution instead of a module-local one.** The root POM has no enforcer; `esapi/pom.xml:78-95` is the only module with rules (`dependencyConvergence`). Add a root 3.6.3 execution at `validate` with `requireMavenVersion [3.9,)`, `requireJavaVersion [17,)` (`README.md:65` documents JDK 17 but nothing rejects a JDK 11 build), `dependencyConvergence`, `banDuplicatePomDependencyVersions` and `requireUpperBoundDeps` (the last three already pass in all five modules with `-Denforcer.fail=false`), then delete the esapi block. `requirePluginVersions` and the lifecycle-plugin pins stay with #104. Acceptance: no module-level enforcer declaration and `mvn clean verify` still passes.

Because this touches release configuration, validate it with one staged and dropped deployment before merging.

**Comment by jmanico** [comment]
A follow-up review of `main` @ `94fd425` found additional items for this issue:

The only workflow is `build.yaml`; the repository has 0 secrets and only the `copilot` and `github-pages` environments. `gh api repos/OWASP/owasp-java-encoder/releases` shows `assets=0` on all four releases, the attestations endpoint returns 404, Central serves no `.sigstore.json` for 1.4.0, and Scorecard scores Signed-Releases and Packaging at -1. Proposed additions, dependent on the KEYS file, the second publisher and #103 landing first:

- [ ] **Project release key.** Generate `OWASP Java Encoder Release <alias>` (rsa4096, sign, 2y) once the UID is decided: `java-encoder@owasp.org` does not exist today, so either OWASP creates it or the key uses an existing `@owasp.org` address. Criterion: key on keyserver.ubuntu.com and keys.openpgp.org and in `KEYS` with a rotation note.
- [ ] **`release` environment.** Both maintainers as required reviewers, `prevent_self_review: true`, deployment policy restricted to `v*` tags, and `CENTRAL_USERNAME`, `CENTRAL_TOKEN`, `MAVEN_GPG_KEY`, `MAVEN_GPG_PASSPHRASE` as environment-scoped secrets. Criterion: `gh api repos/OWASP/owasp-java-encoder/environments/release` shows two required reviewers and the `v*` tag policy.
- [ ] **`.github/workflows/release.yaml`.** `workflow_dispatch` with a version input, `environment: release`, `contents: read` at top level and `contents: write, id-token: write, attestations: write` on the job, SHA-pinned (#102) `actions/checkout` v7.0.1, `actions/setup-java` v6.0.1, `actions/attest-build-provenance` v4.2.2 and `softprops/action-gh-release` v3.0.3. Runs `mvn -B -ntp clean deploy -DperformRelease=true -Dgpg.signer=bc`, which needs the tooling bump already listed above to land as `maven-gpg-plugin` 3.2.8 (the `bc` signer) and `central-publishing-maven-plugin` 0.11.0; `autoPublish=false` (`pom.xml:387`) stays. Criterion: a dry run stages and drops a Portal deployment.
- [ ] **Plugin dependency override.** The 0.11.0 POM still declares `jackson-databind` 2.16.1 and `httpclient5` 5.3.1 (`httpcore5` 5.2.4), so the bump alone leaves known-vulnerable versions in the release plugin. Criterion: plugin-level `<dependencies>` force jackson-databind/jackson-core >= 2.18.8, httpclient5 >= 5.6.3, httpcore5/httpcore5-h2 >= 5.4.3; report upstream to Sonatype.
- [ ] **Provenance, SBOM, release assets.** Attest the four jars, add `cyclonedx-maven-plugin` 2.9.3 `makeAggregateBom`, attach jars, `.asc`, `.sha256` and `bom.json` to the GitHub release. Until the build is reproducible (#103), the attestation must come from the same run that deploys. Criterion: `gh attestation verify encoder-<v>.jar --owner OWASP` passes; Scorecard Signed-Releases and Packaging leave -1.
- [ ] **Optional Sigstore bundles.** `dev.sigstore:sigstore-maven-plugin` 2.3.0 `sign` in the release profile; Sonatype validates `.sigstore.json` while PGP stays mandatory.
- [ ] **RELEASING.md.** `gh workflow run release.yaml -f version=<v>`, the Portal publish step, the laptop path as fallback, and consumer verification: `gh attestation verify` plus `gpg --import KEYS && gpg --verify`.

Related: #102, #103

Suggested target: 1.5.0
